### ISSUE TITLE
Cart checkout stacks up items incorrectly

### ISSUE THREAD

**Issue by DejanPelzel** [BillingServ/Bug-Tracking#3]
I go to https://dev.onlinebillingform.com/order/Fruits
I then click Add to cart
I go back to https://dev.onlinebillingform.com/order/Fruits and add it to cart again

The checkout cart page is now displayed.
The item quantity shows as 1, but if I now click on the red X icon, the page reloads, but the Pineaple is still in there. I have to click the delete as many times as I have clicked on the Add to cart, looks like these are stacked.

**Comment by BillingServ** [comment]
Thanks @DejanPelzel this has now been fixed!
