### ISSUE TITLE
Checkout page displays no error message when no billing info is entered

### ISSUE THREAD

**Issue by DejanPelzel** [BillingServ/Bug-Tracking#4]
When I proceed to the checkout page and don't enter any info and just click on the confirm payment, simply nothing happens. Pretty sure there should be an error telling the user what's missing.

![screencapture-dev-onlinebillingform-checkout-2018-08-03-18_16_36](https://user-images.githubusercontent.com/1392401/43653812-7f839c04-9749-11e8-9c27-265b796ed729.png)

**Comment by BillingServ** [comment]
Thanks for this report, this has now been fixed and all error messages are displayed correctly.
