### ISSUE TITLE
Deleting todo list item not working

### ISSUE THREAD

**Issue by DejanPelzel** [BillingServ/Bug-Tracking#9]
![delete todolist](https://user-images.githubusercontent.com/1392401/43654144-9ac4ab6a-974a-11e8-9521-8a42fdca3d0a.PNG)
I am unable to delete a todo list item, simply nothing happens.

**Comment by BillingServ** [comment]
Thanks for this @DejanPelzel but we are removing the todo list. Which has now been completed :)
